config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :posts do
    member do
      get :delete
    end
    
    resources :comments do
    end
  end
  
  resources :follows do
    member do
      get :delete
      get :followers
      get :following
    end
  end
  
  devise_for :users, :path_prefix => 'd'
  
  resources :users do
    member do
      get :delete
      get :notifications
      put :notifications_edit
    end
  end

   root 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :posts

  has_many :follows, foreign_key: 'follower_id'
  has_many :followed_users, through: :follows
  has_many :inverse_follows, :class_name => "Follow", foreign_key: 'followed_user_id'
  has_many :followers, through: :inverse_follows, source: :follower
  
  has_attached_file :avatar, styles: { large: "600x600>", medium: "300x300>", small: "150x150>", xsmall: "100x100#", thumb: "50x50#", mobile: "80x80>"}, 
      :default_url => "missing.jpg"
      
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates_uniqueness_of :username
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "public"
  
  before_action :authenticate_user!
  before_action :verify_is_admin, :except => [:show, :notifications]
  
  def index
    @users = User.order("last_name ASC")
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def notifications
    @user = User.find(params[:id])
    restrict_access if @user.id != current_user.id
  end
  
  def notifications_edit
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:email_when_comment_made, 
      :email_when_following_posts))
      flash[:notice] = "User updated successfully"
      redirect_to root_path
    else
      flash[:notice] = "Error, User not updated successfully"
      render("notifications")
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User updated successfully"
      redirect_to root_path
    else
      flash[:notice] = "Error, User not updated successfully"
      render("edit")
    end
  end
  
  def delete
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    @follows = @user.follows
    @Inverse_follows = @user.inverse_follows
    @follows.destroy_all
    @Inverse_follows.destroy_all
    if @user.destroy
      flash[:notice] = "User deleted successfully"
      redirect_to root_path
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User added successfully"
      redirect_to(users_path)
    else
      flash[:notice] = "Error. User not added"
      render("new")
    end
  end

  def verify_is_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC")
  end
  
  private
  
  def user_params
    params.require(:user).permit(:first_name, 
      :last_name, :username, :email, :password, :password_confirmation, :admin, :avatar)
  end
  
  def restrict_access
    redirect_to root_path 
    flash[:notice] = "Access denied"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-group">
	<%= f.label(:first_name, "First name")%>
	<%= f.text_field(:first_name, :class=>"form-control") %>
</div>
	
<div class="form-group">
	<%= f.label(:last_name, "Last name")%>
	<%= f.text_field(:last_name, :class=>"form-control") %>
</div>
	
<div class="form-group">	
	<%= f.label(:username, "Username")%>
	<%= f.text_field(:username, :class=>"form-control") %>
</div>

<div class="form-group">	
	<%= f.label :avatar %><br />
	<%= f.file_field :avatar %>
    <%= image_tag @user.avatar.url(:thumb) %>
</div>
	
<div class="form-group">
	<%= f.label(:email, "Email")%>
	<%= f.text_field(:email, :class=>"form-control") %>
</div>
	
<div class="checkbox">
	<label>
		<%= f.check_box(:admin) %>
		Is Admin?
	</label>
</div>

<div class="form-group">	
	<%= f.label(:password, "Password")%>
	<%= f.password_field(:password, :class=>"form-control") %>
</div>
	
<div class="form-group">	
	<%= f.label(:password_confirmation, "Password confirmation")%>
	<%= f.password_field(:password_confirmation, :class=>"form-control") %>
</div>

app/views/users/delete.html.erb
<div class="col-xs-12 post-index-title">
  <h1 class="page_title">Delete User</h1>
</div>

<div class="col-xs-12"  id="create-button">
	<%= link_to("<< Back to user index", users_path, :class => 'btn btn-danger') %>
</div>

<div class="col-xs-12"  id="create-button">
	<h2>Delete User</h2>
	
	<%= form_for(:user, :url => user_path, :html => { :method => :delete }) do |f| %>
	<table class ="table table-bordered table-hover" summary="Subject detail view">
		<tr>
			<th>Username</th>
			<td><%= @user.username %><td>
		</tr>
	</table>
	
	<div class="form-buttons pad">
		<p id="user">Are you sure you want to delete the above user</p>
		<%= submit_tag("Delete user" , :id=> 'submit-cancel-user-devide', :class=>"btn btn-danger") %>
	</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Edit User</h1>
</div>

<%= link_to("Admin Section", users_path, :class => 'btn btn-primary', :id=>"create-button") %>

<div class="col-xs-12 user_create">
	<div class="col-xs-12">
		<h2>Edit user</h2>
	</div>
	
	<div class="col-xs-10">
		<%= form_for(:user, :url => user_path, :html => {:method => :put}) do |f| %>
		
		<%= render(:partial => "form", :locals => {:f => f})%>
		
		<div class="form-buttons pad">
			<%= submit_tag "Update user", :class => 'btn btn-success'%>
		</div>
		<% end %>
	</div>
	
</div>

app/views/users/index.html.erb
<div class="col-xs-12 post-index-title">
  <h1 class="page_title">Admin Index</h1>
</div>
<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>
<br />
<%= link_to "+ Add user", new_user_path, :class => 'btn btn-success', :id=>"create-button" %>

<div class="col-xs-12 users_index">
	<div class="col-xs-12">
		<h2 class="page_subtitle">List</h2>
	</div>
	
	<div class="results-found"> <%= pluralize(@users.size, 'user') %> found </div>
	<div class="table-responsive">
		<table class ="table table-bordered table-hover footable" summary="Users list">
		<thead>
			<tr class="header">
				<th class="listing_header">Avatar</th>
				<th class="listing_header" data-hide="phone">First name</th>
				<th class="listing_header" data-hide="phone">Last name</th>
				<th class="listing_header">Username</th>
				<th class="listing_header" data-hide="phone">Email</th>
				<th class="listing_header" data-hide="phone">Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr class= "<%= cycle('impar', 'par')%> id="joder">
				<td class ="listing_def"><%= image_tag user.avatar.url(:xsmall) %></td>
				<td class ="listing_def"><%= user.first_name %></td>
				<td class ="listing_def"><%= user.last_name %></td>
				<td class ="listing_def"><%= user.username %></td>
				<td class ="listing_def"><%= user.email %></td>
				<td class="actions">
					<%= link_to "Edit user", edit_user_path(:id => user.id), :class => 'action edit' %>
					<%= link_to("Delete user", delete_user_path(user.id), :class => 'action delete')%>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	  
	</div>
</div>

app/views/users/new.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Create User</h1>
</div>

<div class="col-xs-12"  id="create-button">
	<%= link_to("< Back to List", users_path, :class => 'btn btn-danger') %>
</div>

<div class="col-xs-12 user_create">
	<div class="col-xs-12">
		<h2>Add user</h2>
	</div>
	
	<div class="col-xs-10">
		<%= form_for(:user, :url => users_path) do |f| %>
		
		<%= render(:partial => "form", :locals => {:f => f})%>
	
		<div class="form-buttons pad">
			<%= submit_tag("Add user", :class => 'btn btn-success')%>
		</div>
		<% end %>
	</div>
</div>

app/views/users/notifications.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Edit User</h1>
</div>

<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>

<div class="col-xs-12 user_create">
	<div class="col-xs-12">
		<h2>Edit user</h2>
	</div>
	
	<div class="col-xs-10">
		<%= form_for(:user, :url => notifications_edit_user_path, :html => {:method => :put}) do |f| %>
		
		<div class="checkbox">
			<label>
				<%= f.check_box(:email_when_comment_made) %>
				Receive an email notification when a comment is made on your posts?
			</label>
		</div>
		
		<div class="checkbox">
			<label>
				<%= f.check_box(:email_when_following_posts) %>
				Receive an email notification when followed author makes a new post
			</label>
		</div>
		
		<div class="form-buttons pad">
			<%= submit_tag "Update user", :class => 'btn btn-success'%>
		</div>
		<% end %>
	</div>
	
</div>

app/views/users/show.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Subscriptions</h1>
</div>

<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>

<div class="">
	<div class="row">
		<div class="col-xs-12 col-sm-4 col-sm-offset-1 subscription-details">
			<div class="col-xs-12">
				<%= image_tag @user.avatar.url(:medium), :class => "img-responsive" %>
			</div>
			<div class="col-xs-12 follow-info">
				<div class="col-xs-6">
					<p>Followers:</p>
					<%= link_to @user.followers.count, followers_follow_path(@user.id) %>
				</div>
				<div class="col-xs-6">
					<p>Following:</p>
					<%= link_to @user.followed_users.count, following_follow_path(@user.id) %>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 subscription-details custom-collapse">
			<section>
				<button class="collapse-toggle visible-xs btn btn-default detail-button" type="button" data-toggle="collapse" data-parent="custom-collapse" data-target="#side-menu-collapse" id="ogi">
				   <span class="ogi2">Show Details</span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				</button>
				<ul class="list-group collapse" id="side-menu-collapse">
				<% @posts.each do |post| %>
					<li class="list-group-item">
						<div class="row">
							<div class="col-sm-12">
								<h2 class="post-author"><%= post.author %></h2>
							</div>
							<div class="col-sm-12">
								<%= link_to post.title, post_path(post.id) %>
								<p>Posted at: <%= l post.created_at, :format => :short %></p>
							</div>
						</div>
					</li>
				<% end %>
				</ul>
			</section>
		</div>
	</div>
</div>