config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :posts do
    member do
      get :delete
    end
    
    resources :comments do
    end
  end
  
  resources :follows do
    member do
      get :delete
      get :followers
      get :following
    end
  end
  
  devise_for :users, :path_prefix => 'd'
  
  resources :users do
    member do
      get :delete
      get :notifications
      put :notifications_edit
    end
  end

   root 'posts#index'

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  
  #validates :name, :presence => true, :uniqueness => true
  validates_uniqueness_of :follower_id, :scope => :followed_user_id
  
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :followed_user, class_name: 'User', foreign_key: 'followed_user_id'
  has_many :followed_posts, through: :followed_user, source: :posts
 
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  layout "public"
  
  before_action :authenticate_user!
  
  def index
    @follow = @user.follows.find_by(params[:followed_user_id])
  end
  
  def create
    @user = User.find(params[:follower_id])
    @follow = Follow.new(params.permit(:follower_id, :followed_user_id))
    @post = Post.find(params[:post_id])
    if @follow.save
      followed_user = User.find(params[:followed_user_id])
      flash[:notice] = "You now follow '#{followed_user.username}'"
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end
  
  def destroy
    @user = User.find(params[:follower_id])
    if !params[:post_id].blank?
      @post = Post.find(params[:post_id])
    end
    @follow = @user.follows.find_by(params[:followed_user_id])
    @follow.destroy
    respond_to do |format|
        format.html { redirect_to :back }
        format.js
    end
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.order("username ASC")
  end
  
  def following
    @user = User.find(params[:id])
    @following = @user.followed_users.order("username ASC")
  end
  
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<%= button_to "Follow", follows_path(:follower_id => @user.id, :followed_user_id => @post.user_id, :post_id => @post.id), :class=>"btn btn-info", :id=>"follow-btn", remote:true %>

app/views/follows/_unfollow.html.erb
<%= button_to "Unfollow", follow_path(@post, :follower_id => @user.id, :followed_user_id => @post.user_id, :post_id => @post.id), :class=>"btn btn-warning", :id=>"unfollow-btn", remote:true, :method => :delete %>

app/views/follows/create.js.erb
$('#follow').html("<%= j render "follows/unfollow" %>")

app/views/follows/destroy.js.erb
$('#follow').html("<%= j render "follows/follow" %>")

app/views/follows/followers.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Subscriptions</h1>
</div>

<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>


<div class="">
	<div class="row">
		<div class="col-xs-12 col-sm-4 col-sm-offset-1 subscription-details">
			<div class="col-xs-12">
				<%= image_tag @user.avatar.url(:medium), :class => "img-responsive" %>
			</div>
			<div class="col-xs-12 follow-info">
				<div class="col-xs-6" id="clickable">
					<p>Followers:</p>
					<%= link_to @user.followers.count, followers_follow_path(@user.id) %>
				</div>
				<div class="col-xs-6">
					<p>Following:</p>
					<%= link_to @user.followed_users.count, following_follow_path(@user.id) %>
				</div>
			</div>
			<div class="col-xs-12">
				<h3>Followers:</h3>
				<% @user.followers.each do |follower| %>
					<%= image_tag follower.avatar.url(:thumb) %>
				<% end %>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 subscription-details custom-collapse">
			<section>
				<button class="collapse-toggle visible-xs btn btn-default detail-button" type="button" data-toggle="collapse" data-parent="custom-collapse" data-target="#side-menu-collapse" id="ogi">
				   <span class="ogi2">Show Details</span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				</button>
				<ul class="list-group collapse" id="side-menu-collapse">
				<% @followers.each do |follower| %>
				<li class="list-group-item follower-detail">
					<div class="row followers">
						<div class="col-xs-4 col-sm-4">
							<%= image_tag follower.avatar.url(:xsmall), :class => "img-responsive" %>
						</div>
						<div class="col-xs-4 col-sm-4">
							<p>User Name: <%= link_to follower.username, user_path(follower.id) %></p>
							<p>Number of Posts: <%= follower.posts.count %><p>
						</div>
					</div>
				</li>
				<% end %>
				</ul>
			</section>
		</div>
	</div>
</div>

app/views/follows/following.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Subscriptions</h1>
</div>

<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>


<div class="">
	<div class="row">
		<div class="col-xs-12 col-sm-4 col-sm-offset-1 subscription-details">
			<div class="col-xs-12">
				<%= image_tag @user.avatar.url(:medium), :class => "img-responsive" %>
			</div>
			<div class="col-xs-12 follow-info">
				<div class="col-xs-6">
					<p>Followers:</p>
					<%= link_to @user.followers.count, followers_follow_path(@user.id) %>
				</div>
				<div class="col-xs-6">
					<p>Following:</p>
					<%= link_to @user.followed_users.count, following_follow_path(@user.id) %>
				</div>
			</div>
			<div class="col-xs-12">
				<h3>Following:</h3>
				<% @user.followed_users.each do |following| %>
					<%= image_tag following.avatar.url(:thumb) %>
				<% end %>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 subscription-details custom-collapse">
			<section>
				<button class="collapse-toggle visible-xs btn btn-default detail-button" type="button" data-toggle="collapse" data-parent="custom-collapse" data-target="#side-menu-collapse" id="ogi">
				   <span class="ogi2">Show Details</span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				   <span class="icon-bar"></span>
				</button>
				<ul class="list-group collapse" id="side-menu-collapse">
				<% @following.each do |followed| %>
					<li class="list-group-item follower-detail">
						<div class="row followers">
							<div class="col-xs-4">
								<%= image_tag followed.avatar.url(:xsmall), :class=>"img-responsive" %>
							</div>
							<div class="col-xs-4">
								<p>User Name: <%= link_to followed.username, user_path(followed.id) %></p>
								<p>Number of Posts: <%= followed.posts.count %><p>
							</div>
							<div class="col-xs-4" >
								<% if current_user.id == @user.id %>
									<% if @subscribed == false %>
											<%= button_to "Follow", follows_path(:follower_id => @user.id, 
												:followed_user_id => followed.id), 
													:class=>"btn btn-info", :id=>"follow-btn", remote:true %>
									<% else %>
							        		<%= button_to "Unfollow", follow_path(followed, :follower_id => @user.id, 
							        			:followed_user_id => followed.id), 
							        				:class=>"btn btn-warning", :id=>"unfollow-btn", 
							        					:method => :delete %>
							    	<% end %>
						    	<% end %>
							</div>
						</div>
					</li>
					<% end %>
				</ul>
			</section>
		</div>
	</div>
</div>