config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :posts do
    member do
      get :delete
    end
    
    resources :comments do
    end
  end
  
  resources :follows do
    member do
      get :delete
      get :followers
      get :following
    end
  end
  
  devise_for :users, :path_prefix => 'd'
  
  resources :users do
    member do
      get :delete
      get :notifications
      put :notifications_edit
    end
  end

   root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  has_many :comments
  has_many :pictures, :dependent => :destroy
  after_destroy :destroy_comments
  
  def destroy_comments
    self.comments.destroy_all
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :find_subject
  
  layout "public"
  
  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per_page(6)
  end

  def show
    @post = Post.find(params[:id])
    
    if user_signed_in? && current_user.followed_users.where(:id => @post.user_id).blank?
      @subscribed = false
    end
  end

  def new
    @post = @user.posts.new(:author => @user.username)
  end
  
  def create
    @post = @user.posts.new(post_params)
    if @post.save
      if params[:images]
        params[:images].each do |im|
          @post.pictures.create(:image => im)
        end
      end
      flash[:notice] = "Post created successfully"
      send_email_to_followers(@user)
      redirect_to(:action => :show, :id => @post.id)
    else
      render("new")
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Post updated successfully"
      redirect_to(:action => :show)
    else
      render("edit")
    end
  end

  def delete
    @post = Post.find(params[:id])
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "Post '#{post.title}' destroyed successfully"
    redirect_to(:action => :index)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :content_type, :author, :pictures)
  end
  
  def logged_id?
    user_signed_in?
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form-group">
	<%= f.label(:author, "Author")%>
	<%= f.text_field(:author, :readonly => :true, :class=>"form-control") %>
</div>	

<div class="form-group">
	<%= f.label(:title, "Title")%>
	<%= f.text_field(:title, :class=>"form-control") %>
</div>	
	
<div class="form-group">
	<%= f.label(:content_type, "Content type")%>
	<%= f.text_field(:content_type, :class=>"form-control") %>
</div>	
	
<div class="form-group">
	<%= f.label(:content, "Content")%>
	<%= f.text_area(:content, :id=>"comment_content", :class=>"form-control") %>
</div>

<div class="form-group">
	<%= f.label(:pictures, "Image")%>
	<%= f.file_field :images, multiple: true, name: "images[]" %>
</div>			

app/views/posts/_post.html.erb
<div class="row" >
	<div class="col-sm-10 col-sm-offset-1 post-space">
		<div class="col-sm-2 col-xs-12 header">
			<%= image_tag post.user.avatar.url(:small), :class =>"img-responsive col-xs-5 col-sm-12" %>
			<h2 class="post-author"><%= post.author %></h2>
			<p class="date-joined">Joined on: <%= l post.user.created_at, :format => :short %>
				<br/>Posts: <%= post.user.posts.count %>
			</p>
		</div>
		<div class="col-sm-10">
			<h3 class="post-title"><%= post.title %></h3>
			<p class="post-content"><%= post.content %></p>
		</div>
		<div class="col-sm-12" id="post-links">
			<ul class="nav nav-pills navbar-right">
				<li role="presentation"><%= link_to("Show Post", post_path(post.id), :class => 'action show')%></li>
				<% if (user_signed_in? && post.author == @user.username) || (user_signed_in? && @user.admin)%>
					<li role="presentation"><%= link_to("Edit", edit_post_path(post.id), :class => 'action edit')%></li>
					<li role="presentation"><%= link_to("Delete", delete_post_path(post.id), :class => 'action delete')%></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/posts/delete.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Delete a post</h1>
</div>

<div class="col-xs-12"  id="create-button">
	<%= link_to("<<Back to list", posts_path, :class => 'btn btn-danger') %>
</div>

<div class="col-xs-12 post create">
	<div class="col-xs-12">
		<h2>Delete Post</h2>
	</div>
	<div class="col-xs-10">
		<%= form_for(:post, :url => post_path(@post.id), :html => { :method => :delete }) do |f| %>
		<table class ="table table-bordered table-hover" summary="Subject detail view">
			<thead>
				<tr class="header">
					<th>Title</th>
					<td><%= @post.title %><td>
				</tr>
				<tr>
					<th>Author</th>
					<td><%= @post.author %><td>
				</tr>
			</thead>
		</table>

		<div class="form-buttons pad">
			<p id="user">Are you sure you want to delete</p>
			<%= submit_tag("Delete Post", :class=>"btn btn-danger") %>
		</div>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Edit Post</h1>
</div>

<div class="col-xs-12"  id="create-button">
	<%= link_to("<< Back to List", posts_path, :class => 'btn btn-danger') %>
</div>

<div class="col-xs-12 user_create">
	<div class="col-xs-12">
		<h2>Edit Post</h2>
	</div>
	
	<div class="col-xs-10">
		<%= form_for(@post) do |f| %>
		
		<%= render(:partial => "form", :locals => {:f => f})%>
		
		<div class="form-buttons pad">
			<%= submit_tag("Update post", :class => 'btn btn-success')%>
		</div>
		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Posts Index</h1>
</div>

<%= link_to("Create new post", new_post_path, :class => "btn btn-primary", :id=>"create-button") %>

<div class="col-sm-12 post index">
	
	<div class="results-found"> <%= pluralize(@posts.size, 'post') %> found </div>
	
	<div id="posts">
		<%= render @posts %>
	</div>
	
	<%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
page = $('<%= j render(@posts) %>').hide().fadeIn(500);
$('#posts').append(page)
<% if @posts.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@posts) %>')
<% else %>
	$('.pagination').remove()
<% end %>

app/views/posts/new.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Create Post</h1>
</div>

<div class="col-xs-12"  id="create-button">
	<%= link_to("<< Back to List", posts_path, :class => 'btn btn-danger') %>
</div>

<div class="col-xs-12 post create">
	<div class="col-xs-12">
		<h2>Create Post</h2>
	</div>
	<div class="col-xs-10">
		<%= form_for(:post, :url =>  posts_path, :html => { :method => :post, multipart: true}) do |f| %>
		
		<%= render(:partial => "form", :locals => {:f => f})%>
	
	<div class="form-buttons pad">
		<%= submit_tag("Create post", :class=> "btn btn-success")%>
	</div>
	<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="col-xs-12 post-index-title">
	<h1>Post Details</h1>
</div>


<%= link_to("Back to posts", posts_path, :class => 'btn btn-primary', :id=>"create-button") %>
<br />
<br />

<div class="post details">
	<div class="col-xs-offset-1 col-xs-11">
	<h2>Post</h2>
	</div>
	<section>
		<div class="col-sm-offset-1 col-sm-10 post-space">
			<div class="col-xs-12 col-sm-12 header">
				<div class="col-xs-5 col-sm-3">
					<%= image_tag @post.user.avatar.url(:small), :class =>"img-responsive" %>
				</div>
				<div class="col-xs-7 col-sm-7">
					<h3 class="post-title"><%= @post.title %></h3>
					<div>
						<h3 class="date-joined">Author: <%= @post.author %>, Posted at: <%= l @post.created_at, :format => :short %>,</h3>
					</div>
				</div>
			</div>
			<div class="post-content-show">
				<p><%= @post.content %></p>
			</div>
			<div class="post-content-show">
				<% @post.pictures.each do |p| %>
					<%= image_tag p.image.url(:thumb) %>
				<% end %>
			</div>
		</div>
	</section>
	<section>
		<div class="col-xs-offset-1 col-xs-11">
		<h2><%= link_to "Comments", "#", :id=>"comments-link" =%></h2>
		</div>
		<div class="col-xs-offset-1 col-xs-11">
			<h3>Leave a comment</h3>
		</div>
		<div class="col-xs-offset-1 col-xs-10">
			<%= form_for(:comment, :url => post_comments_path(@post), remote:true, :html => {:method => :post}) do |f| %>
	
				<%= render(:partial => "comments/form", :locals => {:f => f})%>
		
				<div class="form-buttons">
					<%= submit_tag("Create comment", :class => 'btn btn-default' ) %>
				</div>
			<% end %>
		</div>
		<div div class="col-xs-offset-1 col-xs-11 pad" id="follow">
			<% if user_signed_in? %>
				<% if  @user.id != @post.user_id %>
					<% if @subscribed == false %>
							<%= render :partial=>"follows/follow" %>
					<% else %>
			        		<%= render :partial=>"follows/unfollow" %>
			    	<% end %>
			    <% end %>
			<% end %>
	    </div>
		<div id="comments-sq">
			<% @post.comments.order("created_at DESC").each do |comment| %>
				<%= render comment %>
			<% end %>
		</div>
	</section>
</div>