config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :posts do
    member do
      get :delete
    end
    
    resources :comments do
    end
  end
  
  resources :follows do
    member do
      get :delete
      get :followers
      get :following
    end
  end
  
  devise_for :users, :path_prefix => 'd'
  
  resources :users do
    member do
      get :delete
      get :notifications
      put :notifications_edit
    end
  end

   root 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAgendaApp</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	<p>Hello, <%= current_user.username %></p>
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<%= link_to "Edit account", edit_user_registration_path %>
	<%= link_to "Subscriptions", follow_path %>
	<% else %>
	 <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <% end %>
     <% if !flash[:notice].blank? %>
	     <div class="notice">
	     	<%= flash[:notice] %>
	     </div>
     <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAgendaApp</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	<p>Hello, <%= current_user.username %></p>
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<%= link_to "Edit account", edit_user_registration_path %>
	<% else %>
	 <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <% end %>
     <% if !flash[:notice].blank? %>
	     <div class="notice">
	     	<%= flash[:notice] %>
	     </div>
     <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width" initial-scale="1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<%= javascript_include_tag 'footable', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag('footable.core.css', :media => 'all') %>
	  <title>RailsAgendaApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body id="body">
		<header class="head">
			<div class="container">
				<h1>My Blog App</h1>
			</div>
		</header>
		<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapsemenu" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to "Home", posts_path, :class=>"navbar-brand" %>
				</div>
				<div class="collapse navbar-collapse" id="collapsemenu">
					<ul class="nav navbar-nav" id="nav-links">
						<li id="nav-links"><%= link_to "Admin Section", users_path %></li>	
					</ul>	
					<ul class="nav navbar-nav navbar-right" id="nav-links">		
						<% if user_signed_in? %>
							<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
							<li id="nav-links" class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">Account settings <span class="caret"></span></a>
									<ul class="dropdown-menu">
										<li><%= link_to "User data", edit_user_registration_path %></li>
										<li><%= link_to "Notifications", notifications_user_path(current_user.id) %></li>
									</ul>
							</li>
							<li id="nav-links"><%= link_to "Profile", user_path(current_user.id) %></li>
							<li class="username">Hello, <%= current_user.username %></li>
							<% else %>
							<li id="nav-links"><%= link_to "Sign in", new_user_session_path %></li>
						<% end %>	
					</ul>
				</div>
			</div>
		</nav>
		<section>
		    <% if !flash[:notice].blank? %>
				<div class="notice">
					<%= flash[:notice] %>
				</div>
		    <% end %>
	    </section>
	    <div class="container">
	    	<div class="row">
	    		<div class="col-xs-12 post-index">
					<%= yield %>
				</div>
			</div>
		</div>
	</body>
</html>